import { describe, expect, it } from "vitest";
import {
  DOCUMENT_TYPE_REGISTRY,
  documentTypeById,
  legacyDocumentTypes,
} from "./documentTypeRegistry.js";
import { AUTOFIELD_DEFINITIONS } from "./autofields.js";

const EXPECTED_TYPES = [
  "repair_fiz",
  "annex",
  "design",
  "design_add",
  "reservation",
  "podryad",
  "podryad_annex",
  "avr_r1",
];

describe("document type registry", () => {
  it("matches the numeric date rendered by design and reservation generators", () => {
    expect(documentTypeById("design")?.requiredFieldIds).toContain("contract.dateFull");
    expect(documentTypeById("design")?.requiredFieldIds).not.toContain("contract.dateLong");
    expect(documentTypeById("reservation")?.requiredFieldIds).toContain("contract.dateFull");
    expect(documentTypeById("reservation")?.requiredFieldIds).not.toContain("contract.dateLong");
  });

  it("contains every legal document currently generated by the service", () => {
    expect(DOCUMENT_TYPE_REGISTRY.map(item => item.id)).toEqual(EXPECTED_TYPES);
  });

  it("uses unique stable template ids and declares exports and required fields", () => {
    const ids = DOCUMENT_TYPE_REGISTRY.map(item => item.templateId);
    expect(new Set(ids).size).toBe(ids.length);
    for (const item of DOCUMENT_TYPE_REGISTRY) {
      expect(item.templateId).toMatch(/^[a-z0-9-]+$/);
      expect(item.name.length).toBeGreaterThan(3);
      expect(item.supportedExports).toEqual(expect.arrayContaining(["pdf"]));
      expect(item.requiredFieldIds.length).toBeGreaterThan(0);
      expect(item.source).toBe("legacy-import");
    }
  });

  it("looks up types without inventing unknown definitions", () => {
    expect(documentTypeById("podryad_annex")?.name).toMatch(/подряд/iu);
    expect(documentTypeById("missing")).toBe(null);
    expect(legacyDocumentTypes()).toHaveLength(EXPECTED_TYPES.length);
  });

  it("only references autofields supported by the editor and renderer", () => {
    const supported = new Set(AUTOFIELD_DEFINITIONS.map(field => field.id));
    const unknown = DOCUMENT_TYPE_REGISTRY.flatMap(type => (
      type.requiredFieldIds.filter(fieldId => !supported.has(fieldId)).map(fieldId => `${type.id}:${fieldId}`)
    ));
    expect(unknown).toEqual([]);
  });
});
